let bsrh_presets = [
    {
        'light-background': '#ffe500',
        'light-foreground': '#121212',
        'light-overlap': '#ffca00',
        'light-match-position': '#b79800',
        'dark-background': '#fff068',
        'dark-foreground': '#121212',
        'dark-overlap': '#e8b907',
        'dark-match-position': '#c5b204',
    },
    {
        "dark-background": "#e37437",
        "dark-foreground": "#f8f8f8",
        "dark-match-position": "#e37437",
        "dark-overlap": "#b15a2b",
        "light-background": "#e37437",
        "light-foreground": "#f8f8f8",
        "light-match-position": "#e37437",
        "light-overlap": "#b15a2b",
    },
    {
        "dark-background": "#d05a40",
        "dark-foreground": "#f8f8f8",
        "dark-match-position": "#d05a40",
        "dark-overlap": "#9f4131",
        "light-background": "#d05a40",
        "light-foreground": "#f8f8f8",
        "light-match-position": "#d05a40",
        "light-overlap": "#9f4131",
    },
    {
        "dark-background": "#b3ff31",
        "dark-foreground": "#000000",
        "dark-match-position": "#b3ff31",
        "dark-overlap": "#86c225",
        "light-background": "#b3ff31",
        "light-foreground": "#000000",
        "light-match-position": "#80b624",
        "light-overlap": "#98d82a",
    },
    {
        "dark-background": "#11ff00",
        "dark-foreground": "#444444",
        "dark-match-position": "#11ff00",
        "dark-overlap": "#12d300",
        "light-background": "#11ff00",
        "light-foreground": "#3b3b3b",
        "light-match-position": "#13a500",
        "light-overlap": "#12d300",
    },
    {
        "dark-background": "#0b6d00",
        "dark-foreground": "#ffffff",
        "dark-match-position": "#10a100",
        "dark-overlap": "#12b300",
        "light-background": "#0b6d00",
        "light-foreground": "#ffffff",
        "light-match-position": "#108a00",
        "light-overlap": "#119500",
    },
    {
        "dark-background": "#a7ffeb",
        "dark-foreground": "#000000",
        "dark-match-position": "#a7ffeb",
        "dark-overlap": "#7fc2b1",
        "light-background": "#a7ffeb",
        "light-foreground": "#000000",
        "light-match-position": "#77b5a6",
        "light-overlap": "#91decc",
    },
    {
        "dark-background": "#2dd9fe",
        "dark-foreground": "#000000",
        "dark-match-position": "#2dd9fe",
        "dark-overlap": "#22adc2",
        "light-background": "#2dd9fe",
        "light-foreground": "#000000",
        "light-match-position": "#2dd9fe",
        "light-overlap": "#25b9d3",
    },
    {
        "dark-background": "#2e86bd",
        "dark-foreground": "#f8f8f8",
        "dark-match-position": "#2e86bd",
        "dark-overlap": "#38a9e6",
        "light-background": "#2e86bd",
        "light-foreground": "#f8f8f8",
        "light-match-position": "#2e86bd",
        "light-overlap": "#38a9e6",
    },

    {
        "dark-background": "#ff53cd",
        "dark-foreground": "#ffffff",
        "dark-match-position": "#ff53cd",
        "dark-overlap": "#b13a91",
        "light-background": "#ff53cd",
        "light-foreground": "#ffffff",
        "light-match-position": "#ff53cd",
        "light-overlap": "#c841a2",
    },
    {
        "dark-background": "#9461fd",
        "dark-foreground": "#ffffff",
        "dark-match-position": "#9461fd",
        "dark-overlap": "#6d49bd",
        "light-background": "#9461fd",
        "light-foreground": "#f8f8f8",
        "light-match-position": "#9461fd",
        "light-overlap": "#6d49bd",
    },
    {
        "dark-background": "#79458d",
        "dark-foreground": "#f8f8f8",
        "dark-match-position": "#b76dda",
        "dark-overlap": "#9658b1",
        "light-background": "#79458d",
        "light-foreground": "#f8f8f8",
        "light-match-position": "#79458d",
        "light-overlap": "#9658b1",
    },
    {
        "dark-background": "#000000",
        "dark-foreground": "#ffffff",
        "dark-match-position": "#9d9d9d",
        "dark-overlap": "#585858",
        "light-background": "#000000",
        "light-foreground": "#ffffff",
        "light-match-position": "#000000",
        "light-overlap": "#5d5d5d",
    },
    {
        "dark-background": "#b4b4b4",
        "dark-foreground": "#121212",
        "dark-match-position": "#b4b4b4",
        "dark-overlap": "#939393",
        "light-background": "#b4b4b4",
        "light-foreground": "#000000",
        "light-match-position": "#919191",
        "light-overlap": "#8a8a8a",
    },
    {
        "dark-background": "#ffffff",
        "dark-foreground": "#121212",
        "dark-match-position": "#ffffff",
        "dark-overlap": "#bcbcbc",
        "light-background": "#e2e2e2",
        "light-foreground": "#121212",
        "light-match-position": "#adadad",
        "light-overlap": "#c2c2c2",
    },
]
